# Introduction to Pandas

In this section of the course we will learn how to use pandas for data analysis. You can think of pandas as an extremely powerful version of Excel, with a lot more features. In this section of the course, you should go through the notebooks in this order:

* DataTypes
    * Series
    * DataFrames
* Missing Data
* Operations
* Data Analysis
    * GroupBy
    * Merging,Joining,and Concatenating
* Data Input and Output

## 5. Data Input and Output

This notebook is the reference code for getting input and output, pandas can read a variety of file types using its pd.read_ methods. Let's take a look at the most common data types:

In [ ]:
import numpy as np
import pandas as pd

## CSV

### CSV Input

In [ ]:
df = pd.read_csv('sample_data/california_housing_test.csv')

In [ ]:
df

      longitude  latitude  ...  median_income  median_house_value
0       -122.05     37.37  ...         6.6085            344700.0
1       -118.30     34.26  ...         3.5990            176500.0
2       -117.81     33.78  ...         5.7934            270500.0
3       -118.36     33.82  ...         6.1359            330000.0
4       -119.67     36.33  ...         2.9375             81700.0
...         ...       ...  ...            ...                 ...
2995    -119.86     34.42  ...         1.1790            225000.0
2996    -118.14     34.06  ...         3.3906            237200.0
2997    -119.70     36.30  ...         2.2895             62000.0
2998    -117.12     34.10  ...         3.2708            162500.0
2999    -119.63     34.42  ...         8.5608            500001.0

[3000 rows x 9 columns]

### CSV Output

In [ ]:
df.to_csv('example',index=False)

## Excel
Pandas can read and write excel files, keep in mind, this only imports data. Not formulas or images, having images or macros may cause this read_excel method to crash.

### Excel Input

In [ ]:
!rm -rf GSLPro-Uruguay2022

In [ ]:
# Copy over data from github
%%bash
git clone https://github.com/teb5240/GSLPro-Uruguay2022

Cloning into 'GSLPro-Uruguay2022'...

In [ ]:
# Access a Sample Excel Sheet
!unzip 'GSLPro-Uruguay2022/sampledatafoodsales.zip'

Archive:  GSLPro-Uruguay2022/sampledatafoodsales.zip
replace sampledatafoodsales.xlsx? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [ ]:
pd.read_excel('sampledatafoodsales.xlsx', sheet_name='FoodSales')

     OrderDate Region         City  ... Quantity UnitPrice  TotalPrice
0   2020-01-01   East       Boston  ...       33      1.77       58.41
1   2020-01-04   East       Boston  ...       87      3.49      303.63
2   2020-01-07   West  Los Angeles  ...       58      1.87      108.46
3   2020-01-10   East     New York  ...       82      1.87      153.34
4   2020-01-13   East       Boston  ...       38      2.18       82.84
..         ...    ...          ...  ...      ...       ...         ...
239 2021-12-18   East       Boston  ...       34      2.18       74.12
240 2021-12-21   East       Boston  ...      245      1.87      458.15
241 2021-12-24   East       Boston  ...       30      3.49      104.70
242 2021-12-27   West  Los Angeles  ...       30      1.87       56.10
243 2021-12-30   West  Los Angeles  ...       44      2.84      124.96

[244 rows x 8 columns]

### Excel Output

In [ ]:
df.to_excel('sampledatafoodsales.xlsx', sheet_name='FoodSales')

## HTML

You may need to install htmllib5,lxml, and BeautifulSoup4. In your terminal/command prompt run:

    conda install lxml
    conda install html5lib
    conda install BeautifulSoup4

Then restart Jupyter Notebook.
(or use pip install if you aren't using the Anaconda Distribution)

Pandas can read table tabs off of html. For example:

In [ ]:
!pip3 install lxml
!pip3 install html5lib
!pip3 install BeautifulSoup4

Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (4.2.6)
Requirement already satisfied: html5lib in /usr/local/lib/python3.7/dist-packages (1.0.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.7/dist-packages (from html5lib) (1.15.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.7/dist-packages (from html5lib) (0.5.1)
Requirement already satisfied: BeautifulSoup4 in /usr/local/lib/python3.7/dist-packages (4.6.3)

### HTML Input

Pandas read_html function will read tables off of a webpage and return a list of DataFrame objects:

In [ ]:
URL = 'https://en.wikipedia.org/wiki/Pythonidae'
df = pd.read_html(URL)

In [ ]:
df[1]

                                           Pythonidae                                       Pythonidae.1
0                                                 NaN                                                NaN
1                      Indian python (Python molurus)                     Indian python (Python molurus)
2                           Scientific classification                          Scientific classification
3                                            Kingdom:                                           Animalia
4                                             Phylum:                                           Chordata
5                                              Class:                                           Reptilia
6                                              Order:                                           Squamata
7                                           Suborder:                                          Serpentes
8                                        Superfamily:                                        Pythonoidea
9                                             Family:                          PythonidaeFitzinger, 1826
10                                           Synonyms                                           Synonyms
11  Pythonoidia - Fitzinger, 1826 Pythonoidei - Ei...  Pythonoidia - Fitzinger, 1826 Pythonoidei - Ei...

____

# Great Job!