**If you haven't already, please hit :**

`File` -> `Save a Copy in Drive`

**Copy this notebook to your Google drive, and work on a copy. If you don't do this, your changes won't be saved!**


# Ecommerce Purchases Exercise

In this Exercise you will be given some Fake Data about some purchases done through Amazon! Just go ahead and follow the directions and try your best to answer the questions and complete the tasks. Feel free to reference the solutions. Most of the tasks can be solved in different ways. For the most part, the questions get progressively harder.

Please excuse anything that doesn't make "Real-World" sense in the dataframe, all the data is fake and made-up.

Also note that all of these questions can be answered with one line of code.
____
** Import pandas and read in the Ecommerce Purchases csv file and set it to a DataFrame called ecom. **

In [5]:
!wget https://github.com/caboonie/gsl-uruguay/raw/main/content/week0/Ecommerce%20Purchases # load in the data

--2026-01-08 02:42:01--  https://github.com/caboonie/gsl-uruguay/raw/main/content/week0/Ecommerce%20Purchases
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/caboonie/gsl-uruguay/main/content/week0/Ecommerce%20Purchases [following]
--2026-01-08 02:42:01--  https://raw.githubusercontent.com/caboonie/gsl-uruguay/main/content/week0/Ecommerce%20Purchases
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2745852 (2.6M) [text/plain]
Saving to: ‘Ecommerce Purchases’

Ecommerce Purchases 100%[===================>]   2.62M  --.-KB/s    in 0.07s

2026-01-08 02:42:02 (37.1 MB/s) - ‘Ecommerce Purchases’ saved [2745852/2745852]

**Import Pandas and the Data**

**(It is loaded into your Google Colab Working Directory as "Ecommerce Purchases")**

In [6]:
import pandas as pd
df = pd.read_csv("Ecommerce Purchases")

**Check the head of the DataFrame.**

In [7]:
df.head()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

**How many rows and columns are there?**

In [8]:
rows = df.shape[0]
columns = df.shape[1]
print(f"ROws: {rows} and Colummns: {columns}")

ROws: 10000 and Colummns: 14

**What is the average Purchase Price?**

In [9]:
df.info()
average = df['Purchase Price'].mean()
print(f"the average Purchase Price is {average}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  object
 1   Lot               10000 non-null  object
 2   AM or PM          10000 non-null  object
 3   Browser Info      10000 non-null  object
 4   Company           10000 non-null  object
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  object
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  object
 9   Email             10000 non-null  object
 10  Job               10000 non-null  object
 11  IP Address        10000 non-null  object
 12  Language          10000 non-null  object
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB
the average Purchase Price is 50.347302

**What were the highest and lowest purchase prices?**

In [10]:
max_value = df['Purchase Price'].max()
min_value = df['Purchase Price'].min()
print(f"the highest and lowest purchase prices are: max = {max_value} and min = {min_value}")

the highest and lowest purchase prices are: max = 99.99 and min = 0.0

**How many people have English 'en' as their Language of choice on the website?**

In [11]:
x = df[df['Language'] == 'en'].shape[0]
print(f"people have English 'en' as their Language of choice on the website: {x}")

people have English 'en' as their Language of choice on the website: 1098

**How many people have the job title of "Lawyer"?**

In [12]:
df[df['Job'] == 'Lawyer'].count()
x = df[df['Job'] == 'Lawyer'].shape[0]
print(f"people have English 'en' as their Language of choice on the website: {x}")

people have English 'en' as their Language of choice on the website: 30

**How many people made the purchase during the AM and how many people made the purchase during PM?**

**(Hint: Check out [value_counts()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html))**

In [13]:
df['AM or PM'].value_counts()

AM or PM
PM    5068
AM    4932
Name: count, dtype: int64

**What are the 5 most common Job Titles?**

In [14]:
df['Job'].value_counts().head(5)

Job
Interior and spatial designer        31
Lawyer                               30
Social researcher                    28
Research officer, political party    27
Designer, jewellery                  27
Name: count, dtype: int64

**Someone made a purchase that came from Lot: "90 WT" , what was the Purchase Price for this transaction?**

In [15]:
df[df['Lot'] == '90 WT']['Purchase Price']

513    75.1
Name: Purchase Price, dtype: float64

**What is the email of the person with the following Credit Card Number: 4926535242672853**

In [19]:
df[df['Credit Card'] == 4926535242672853]['Email']

1234    bondellen@williams-garza.com
Name: Email, dtype: object

**How many people have American Express as their Credit Card Provider *and* made a purchase above $95?**

In [26]:
df[
    (df['CC Provider'] == 'American Express') &
    (df['Purchase Price'] > 95)
  ].shape[0]

39

** Hard: How many people have a credit card that expires in 2025? **

In [33]:

r = df['CC Exp Date'].apply(lambda x: x.split('/')[-1] == '25').sum()
print(f"people have a credit card that expires in 2025 is: {r}")

people have a credit card that expires in 2025 is: 1033

** Hard: What are the top 5 most popular email providers/hosts (e.g. gmail.com, yahoo.com, etc...) **

In [32]:
df['Email'].apply(lambda x: x.split('@')[1]).value_counts().head(5)

Email
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64

# Great Job -- you diddily did it! :D